version: '3'

services:
  flask_api:
    build:
      context: .
      dockerfile: Dockerfile.flask_api
    #volumes:
    #  - .:/TextToSQL
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=abc
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
